version: 2

models:
  - name: stg_daily_regional
    description: "Raw daily regional (spatial aggregation box: region) weather data from gold layer"
    columns:
      - name: date
        description: "The date of the weather observation"
        tests:
          - not_null
      - name: region
        description: "The region of the weather observation"
        tests:
          - not_null
  - name: stg_daily_global
    description: "Raw daily global (precise location: latitude, longitude) weather data from gold layer"
    columns:
      - name: date
        description: "The date of the weather observation"
        tests:
          - not_null
      - name: latitude
        description: "The latitude of the weather observation"
        tests:
          - not_null
      - name: longitude
        description: "The longitude of the weather observation"
        tests:
          - not_null
